In [2]:
import math

In [3]:
math.pi

3.141592653589793

In [4]:
math.e

2.718281828459045

In [5]:
math.inf

inf

In [6]:
math.ceil(7.8)

8

In [7]:
math.floor(2.5)

2

In [8]:
float_list = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [9]:
sum(float_list)

0.9999999999999999

In [10]:
math.fsum(float_list)

1.0

In [11]:
math.gcd(30, 20)

10

In [12]:
math.gcd(3343, 223)

1

In [13]:
!pip install numpy

In [14]:
import numpy as np

In [17]:
some_list = [1, 2, 3, 4, 5, 6, 7]

type(some_list)

list

In [19]:
some_array = np.array(some_list)

type(some_array)

numpy.ndarray

In [20]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
ones_array = np.ones(5)

ones_array

array([1., 1., 1., 1., 1.])

In [25]:
range_array = np.arange(8)

range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
reshaped_array = range_array.reshape(2, 4)

reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
reshaped_array = range_array.reshape(4, 2)

reshaped_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [30]:
random_array = np.random.random((4, 5))

random_array

array([[0.85670591, 0.64555986, 0.59990775, 0.60144109, 0.13018412],
       [0.66752852, 0.38406975, 0.81694479, 0.76924647, 0.47255703],
       [0.1846916 , 0.71282396, 0.87639702, 0.4854427 , 0.42636083],
       [0.70155693, 0.2404088 , 0.48033056, 0.33499955, 0.21469115]])

In [31]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
mean = np.mean(range_array)

mean

3.5

In [36]:
median = np.median(range_array)

median

3.5

In [34]:
var = np.var(range_array)

var

5.25

In [35]:
std = np.std(range_array)

std

2.29128784747792

In [48]:
!pip install pandas

In [37]:
import pandas as pd

In [53]:
df = pd.DataFrame({
                    'name': ["John", "Alice", "Bob", "Eileen", "Rob"],
                    'gender': ["Male", "Female", "Male", "Female", "Male"],
                    'age': [45, 20, 30, 14, 67],
                  })

In [54]:
df

name  gender  age
0    John    Male   45
1   Alice  Female   20
2     Bob    Male   30
3  Eileen  Female   14
4     Rob    Male   67

In [55]:
df.describe()

age
count   5.000000
mean   35.200000
std    21.300235
min    14.000000
25%    20.000000
50%    30.000000
75%    45.000000
max    67.000000

In [56]:
subset_df = df[['name', 'age']]

subset_df

name  age
0    John   45
1   Alice   20
2     Bob   30
3  Eileen   14
4     Rob   67

In [57]:
groupby_df = df.groupby(by="gender").count()

groupby_df.head()

name  age
gender           
Female     2    2
Male       3    3